export const DialogProps = {
  AddAuthenticatorAppDialog: {} as any,
  AddEditAddressDialog: {} as any,
  AddEditPermissionDialog: {} as any,
  AddEditRoleDialog: {} as any,
  BaseDialog: {} as any,
  CardAddEditDialog: {} as any,
  ConfirmDialog: {} as any,
  CreateAppDialog: {} as any,
  EnableOneTimePasswordDialog: {} as any,
  PricingPlanDialog: {} as any,
  ReferAndEarnDialog: {} as any,
  ShareProjectDialog: {} as any,
  TwoFactorAuthDialog: {} as any,
  UserInfoEditDialog: {} as any,
  UserUpgradePlanDialog: {} as any,
  VehicleStateDialog: {} as any,
}
